### ISSUE TITLE
Graph Style Sheet section got lost in v3.2

### ISSUE THREAD

**Issue by nicho90** [neo4j/neo4j-browser#533]
Hi there,

I installed today v3.2, but I could not find the **Graph Style Sheet** section anymore. It has disappeared in the neo4j-browser (please see the screenshots below). BUT for people who are currently running into the same problem, you can still use a Cypher query, e.g.
```
:style https://gist.githubusercontent.com/.../grass.css
```
I tried to import the file locally, but it didn't worked, so I uploaded it on Gist.

### v3.1.4
![v3.1.4](https://cloud.githubusercontent.com/assets/5202984/26219325/d574f366-3c0e-11e7-9aaf-73c5ad224b6b.png)

### v3.2
![v3.2](https://cloud.githubusercontent.com/assets/5202984/26219327/d5921a72-3c0e-11e7-950d-5afe22bd28c8.png)

Best and cheerio,
Nicho ✌️

**Comment by AugustasL** [comment]
Yep its gone for me too it's a shame...

**Comment by pe4cey** [comment]
This is fixed in https://github.com/neo4j/neo4j-browser/pull/543
It should go out with the next neo4j release.

**Comment by maddoc1** [comment]
Now I can upload a style, but there is still no way to download the current style

**Comment by dijikul** [comment]
Still a problem in v3.2.3.  All online instructions on how to modify GRASS Styles are nonfunctional in my instance... 
Version: 3.2.3
Edition: Community
